### ISSUE TITLE
Hi~ I wonder are you still interested in this project?

### ISSUE THREAD

**Issue by zdhNarsil** [JSeam2/Neural-Ordinary-Differential-Equations#2]
the sequel of neural ODE, the JJFORD, has been released out, which seems interesting. I wonder if you are interested in its implementation?

**Comment by RahulBhalley** [comment]
@zdhNarsil please link the arXiv link to JJFORD if possible.

**Comment by zdhNarsil** [comment]
> @zdhNarsil please link the arXiv link to JJFORD if possible.

https://arxiv.org/abs/1810.01367

**Comment by JSeam2** [comment]
I work on this project in my spare time so it might take quite a while to find free time to dedicate to this. I will try to expedite the efforts. When I embarked on this I did not expect anyone to be interested.
